foreground         #c3c4c7
background         #12161f
background_opacity 1.0
cursor             #c3c4c7

active_tab_foreground     #12161f
active_tab_background     #c3c4c7
inactive_tab_foreground   #c3c4c7
inactive_tab_background   #12161f

active_border_color   #c3c4c7
inactive_border_color #12161f
bell_border_color     #465e90

color0       #12161f
color8       #5e6572
color1       #465e90
color9       #5E7EC1
color2       #4b6a7f
color10      #648EAA
color3       #527e97
color11      #6EA9CA
color4       #5d91a4
color12      #7DC2DB
color5       #737b7a
color13      #9AA5A3
color6       #738a96
color14      #9AB9C9
color7       #91959c
color15      #c3c4c7
