#font_family = JetBrainsMono

#shell zsh
#shell_integration disabled

remember_window_size no

cursor_shape beam

allow_remote_control yes

#background_opacity 0.9

#scrollbar_handle_opacity 	0
#scrollbar_track_opacity	 	0
#scrollbar_track_hover_opacity 	0

#confirm_os_window_close		0

#sync_to_monitor no

#include ./theme.conf
