# Desktop profile: two external displays with alternating workspaces.
monitor=,preferred,auto,1.0
monitor=DP-1,1920x1080@60.00,1920x100,1.0
monitor=DP-3,1920x1080@75.00,0x0,1.0

workspace=1,monitor:DP-3
workspace=2,monitor:DP-1
workspace=3,monitor:DP-3
workspace=4,monitor:DP-1
workspace=5,monitor:DP-3
workspace=6,monitor:DP-1
workspace=7,monitor:DP-3
workspace=8,monitor:DP-1
workspace=9,monitor:DP-3
workspace=10,monitor:DP-1
